/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Control.Abarrote;
import Control.Alimento;
import Control.Electronicos;
import Control.Tipo;
import Modelo.ModeloAbaMayorista;
import Modelo.ModeloAbaPublico;
import Modelo.ModeloAliMayorista;
import Modelo.ModeloAliPublico;
import Modelo.ModeloEmpleado;
import Modelo.ModeloMayorista;
import Modelo.ModeloPublico;
import Modelo.ModeloTabla;
import Modelo.ModeloeleMayprista;
import Modelo.ModeloelePublico;
import Modelo.Modelofinal;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author manel
 */
public class Formulaciondepedidos extends javax.swing.JPanel {

    /**
     * Creates new form Formulaciondepedidos
     */
        public String cliente;
        private Alimento ali;
        private Abarrote aba;
        private Electronicos ele;
        public List<Object []> objeto=new ArrayList<Object[]>();
        private Tipo seleccion;
    public Formulaciondepedidos() {
       // jTable1.setVisible(false);
       
        initComponents();
         combo();
        if(jComboBox1.getSelectedIndex()==0){
                             ali=new Alimento();
                             seleccion=new Alimento();
                            }else if(jComboBox1.getSelectedIndex()==1){
                               aba=new Abarrote();
                               seleccion=new Abarrote();
                            }else if(jComboBox1.getSelectedIndex()==2){
                              ele=new Electronicos();
                              seleccion=new Electronicos();
                            }
        
    }
    public void setCliente(String s){
      this.cliente=s;  
    }
    public ModeloTabla model(){
       if(cliente.equals("Publico")){
           return new ModeloPublico(seleccion.muestraArticulos(cliente));
       }else if(cliente.equals("Mayorista")){
           return new ModeloMayorista(seleccion.muestraArticulos(cliente));
       }  
       else if (cliente.equals("Empleado")){
           return new ModeloEmpleado(seleccion.muestraArticulos(cliente));    
               }else{
           return null;
       }
    }
        
   
   /* public ModeloTabla Modelo(){
      //ModeloTabla m=null;
      if(cliente.equals("Publico") && jComboBox1.getSelectedIndex()==0){
          return  new ModeloAliPublico(ali.muestraArticulos(cliente));
      }else if(cliente.equals("Publico") && jComboBox1.getSelectedIndex()==1){
           return  new ModeloAbaPublico(aba.muestraArticulos(cliente));
      }else if(cliente.equals("Publico") && jComboBox1.getSelectedIndex()==2){
           return  new ModeloelePublico(ele.muestraArticulos(cliente));
      }else if(cliente.equals("Mayorista") && jComboBox1.getSelectedIndex()==0){
          return new ModeloAliMayorista(ali.muestraArticulos(cliente));
      }else if(cliente.equals("Mayorista") && jComboBox1.getSelectedIndex()==1){
          return new ModeloAbaMayorista(aba.muestraArticulos(cliente)); 
      }else if(cliente.equals("Mayorista") && jComboBox1.getSelectedIndex()==2){
          return new ModeloeleMayprista(ele.muestraArticulos(cliente));
      }else if(cliente.equals("Empleado") && jComboBox1.getSelectedIndex()==0){
         return new ModeloAliMayorista(ali.muestraArticulos(cliente)); 
      }else if(cliente.equals("Empleado") && jComboBox1.getSelectedIndex()==1){
           return new ModeloAbaMayorista(aba.muestraArticulos(cliente)); 
      }else if(cliente.equals("Empleado") && jComboBox1.getSelectedIndex()==2){
         return new ModeloeleMayprista(ele.muestraArticulos(cliente));  
      }
      else{
          return null;
      }
      //return m;
          
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Formulacion de pedidos"));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentos", "Abarrotes", "Electrodomesticos" }));

        jButton1.setText("Formular Pedidos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Pedidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // TODO add your handling code here:
      jTable1.setModel(model());
      jComboBox1.setEnabled(false);
      jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     int cuenta=0;
       for(int n=0;n<jTable1.getRowCount();n++){
           
           Object ob[]=new Object[3];
           int aux=(int)jTable1.getValueAt(n, jTable1.getColumnCount()-2);
           if(aux>0){
             ob[0]=jTable1.getValueAt(n, 0);
             ob[1]=jTable1.getValueAt(n, jTable1.getColumnCount()-2);
             ob[2]=jTable1.getValueAt(n, jTable1.getColumnCount()-1);
             objeto.add(ob);
             cuenta=cuenta+1;
           }
               
        }
       if(cuenta>0){
        this.removeAll();
        FinalizarPedido fp=new FinalizarPedido();
        fp.setModelo(new Modelofinal(objeto));
        fp.setSize(600, 415);
        this.add(fp);
        this.repaint();
       }else{
           JOptionPane.showMessageDialog(null, "NO hubo ningun pedido");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

     public void combo(){
        /* jComboBox1.addItemListener(
                 new ItemListener() { // anonymous inner class
                    // handle JComboBox event
                    public void itemStateChanged(ItemEvent event) {
        )*/
          jComboBox1.addItemListener(
          new ItemListener() { // anonymous inner class
                    // handle JComboBox event
                    public void itemStateChanged(ItemEvent event) {
                        if (event.getStateChange() == ItemEvent.SELECTED) {
                         if(jComboBox1.getSelectedIndex()==0){
                             ali=new Alimento();
                             seleccion=new Alimento();
                            }else if(jComboBox1.getSelectedIndex()==1){
                               aba=new Abarrote();
                               seleccion=new Abarrote();
                            }else if(jComboBox1.getSelectedIndex()==2){
                              ele=new Electronicos();   
                              seleccion=new Electronicos();
                            }
                         
                        }
                    }
                        
                    }
);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
